# Generated by Django 4.0.4 on 2022-06-05 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('entity', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Account Name')),
                ('code', models.IntegerField(verbose_name='Account Head Code')),
                ('detilsinbs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Details in Balance Sheet')),
                ('balanceType', models.CharField(max_length=50, null=True, verbose_name='Balance Type')),
                ('drcreffect', models.CharField(max_length=20, verbose_name='Debit/credit Effect')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('group', models.CharField(choices=[('Balance_sheet', 'Balance Sheet'), ('P/l', 'Profit Loss')], max_length=50, null=True)),
                ('accountheadsr', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.accounthead', verbose_name='Account head Sr')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account head',
                'verbose_name_plural': 'Account Heads',
            },
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gstno', models.CharField(max_length=50, null=True, verbose_name='Gst No')),
                ('accountName', models.CharField(max_length=50, null=True, verbose_name='Account Name')),
                ('address1', models.CharField(max_length=50, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(max_length=50, null=True, verbose_name='Address Line 2')),
                ('openingBcr', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Opening Balance Cr')),
                ('openingBdr', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Opening Balance Dr')),
                ('contactNo', models.IntegerField(verbose_name='Contact No')),
                ('emailid', models.CharField(max_length=50, null=True, verbose_name='Email id')),
                ('agent', models.CharField(max_length=50, null=True, verbose_name='Agent/Group')),
                ('pan', models.CharField(max_length=50, null=True, verbose_name='PAN')),
                ('tOverlow10', models.BooleanField(verbose_name='Turnover below 10 lac')),
                ('approved', models.BooleanField(verbose_name='Wheather aproved')),
                ('Tdsno', models.CharField(max_length=50, null=True, verbose_name='Tds A/c No')),
                ('accountHead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.accounthead')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='geography.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.district')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('owner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.state')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='account_detials2',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial.account')),
                ('contactperson', models.CharField(max_length=50, null=True, verbose_name='Contact Person')),
                ('deprate', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Depreciaion Rate')),
                ('tdsrate', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='TDS Rate')),
                ('gstshare', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Adhaar No')),
                ('quanity1', models.IntegerField(verbose_name='Quanity 2')),
                ('BanKAcno', models.IntegerField(verbose_name='Bank A/c No')),
                ('composition', models.BooleanField(verbose_name='Bank A/c No')),
                ('owner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Detail2',
                'verbose_name_plural': 'Account Details2',
            },
        ),
        migrations.CreateModel(
            name='account_detials1',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial.account')),
                ('accountno', models.CharField(max_length=50, null=True, verbose_name='Account no')),
                ('rtgsno', models.CharField(max_length=50, null=True, verbose_name='Rtgs no')),
                ('bankname', models.CharField(max_length=50, null=True, verbose_name='Bank Name')),
                ('Adhaarno', models.CharField(max_length=50, null=True, verbose_name='Adhaar No')),
                ('saccode', models.CharField(max_length=50, null=True, verbose_name='SAC Code')),
                ('owner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Detail1',
                'verbose_name_plural': 'Account Details1',
            },
        ),
    ]
