# Generated by Django 4.0.4 on 2022-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_accounthead_balancetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthead',
            name='Description',
            field=models.CharField(max_length=20, null=True, verbose_name='Description'),
        ),
    ]
