# Generated by Django 4.0.4 on 2022-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_accounthead_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthead',
            old_name='DrcrEffect',
            new_name='drcrrffect',
        ),
        migrations.RemoveField(
            model_name='accounthead',
            name='Description',
        ),
        migrations.AddField(
            model_name='accounthead',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
    ]
