# Generated by Django 4.0.4 on 2022-06-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_rename_drcreffect_accounthead_drcrrffect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthead',
            old_name='drcrrffect',
            new_name='DrcrEffect',
        ),
    ]
