# Generated by Django 4.0.4 on 2022-06-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_rename_drcrrffect_accounthead_drcreffect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthead',
            old_name='DrcrEffect',
            new_name='drcreffect',
        ),
    ]
