# Generated by Django 4.0.4 on 2022-06-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_rename_drcreffect_accounthead_drcreffect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounthead',
            old_name='accountHeadSr',
            new_name='accountheadsr',
        ),
    ]
