# Generated by Django 4.0.4 on 2022-06-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='cityCode',
            new_name='citycode',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='cityName',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='CountryCode',
            new_name='countrycode',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='CountryName',
            new_name='countryname',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='districtCode',
            new_name='districtcode',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='districtName',
            new_name='districtname',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='StateCode',
            new_name='statecode',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='StateName',
            new_name='statename',
        ),
    ]
