# Generated by Django 4.0.4 on 2022-06-05 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='inventory.album')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pcategortyname', models.CharField(max_length=255, verbose_name='Product Category')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('maincategory', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='Main category')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productname', models.CharField(max_length=255, verbose_name='Product Name')),
                ('productdesc', models.TextField(verbose_name='Product Desc')),
                ('openingstockqty', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Opening Stock Qty')),
                ('openingstockboxqty', models.IntegerField(blank=True, default=True, verbose_name='Box/Pcs')),
                ('openingstockvalue', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Opening Stock Value')),
                ('purchaserate', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Purchase Rate')),
                ('prlesspercentage', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Less %')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='M.R.P')),
                ('mrpless', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Less %')),
                ('salesprice', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Sale Price')),
                ('totalgst', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Less %')),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='C GST @')),
                ('cgstcess', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Cess Qty')),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='S GST @')),
                ('sgstcess', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10, verbose_name='Cess Qty')),
                ('is_stockable', models.BooleanField(default=True)),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('productcategory', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategory', verbose_name='Product Category')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
