# Generated by Django 3.2.9 on 2022-01-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='openingStockBox',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
