# Generated by Django 4.0.4 on 2022-06-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='pcategortyname',
            new_name='pcategoryname',
        ),
    ]
