# Generated by Django 4.0.4 on 2022-08-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productdesc',
            field=models.CharField(max_length=100, null=True, verbose_name='product desc'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
    ]
