# Generated by Django 3.2.9 on 2022-01-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220115_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
    ]
