# Generated by Django 3.2.9 on 2022-02-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('created_at',)},
        ),
    ]
