# Generated by Django 4.0.4 on 2022-08-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity'),
        ),
    ]
