# Generated by Django 4.0.4 on 2022-08-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rolepriv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mainmenu', models.ManyToManyField(null=True, related_name='mainmenus', to='Authentication.mainmenu')),
                ('role', models.ManyToManyField(null=True, related_name='roles', to='Authentication.role')),
            ],
            options={
                'verbose_name': 'Role Priveledge',
                'verbose_name_plural': 'Role Priveledges',
            },
        ),
    ]
