# Generated by Django 4.0.4 on 2022-08-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_rolepriv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepriv',
            name='mainmenu',
        ),
        migrations.AddField(
            model_name='rolepriv',
            name='mainmenu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainmenus', to='Authentication.mainmenu'),
        ),
        migrations.RemoveField(
            model_name='rolepriv',
            name='role',
        ),
        migrations.AddField(
            model_name='rolepriv',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Authentication.role'),
        ),
    ]
