# Generated by Django 4.1 on 2022-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_remove_rolepriv_mainmenu_rolepriv_mainmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepriv',
            name='mainmenu',
        ),
        migrations.RemoveField(
            model_name='rolepriv',
            name='role',
        ),
        migrations.AddField(
            model_name='rolepriv',
            name='mainmenu',
            field=models.ManyToManyField(null=True, related_name='mainmenus', to='Authentication.mainmenu'),
        ),
        migrations.AddField(
            model_name='rolepriv',
            name='role',
            field=models.ManyToManyField(null=True, related_name='roles', to='Authentication.role'),
        ),
    ]
