# Generated by Django 3.2.9 on 2022-04-17 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='owner',
        ),
        migrations.AddField(
            model_name='entity',
            name='userid',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
