# Generated by Django 3.2.9 on 2022-04-26 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0002_auto_20220417_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='userid',
        ),
        migrations.AddField(
            model_name='entity',
            name='createdby',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
