# Generated by Django 3.2.9 on 2022-05-20 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0006_auto_20220520_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='entity_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdby', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_user_requests_created', to=settings.AUTH_USER_MODEL)),
                ('entity', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='entityUser',
        ),
    ]
