# Generated by Django 3.2.9 on 2022-05-20 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0009_alter_entity_user_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity_user',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entity_user_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
