# Generated by Django 3.2.9 on 2022-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_alter_entity_user_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity_user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='entity_user',
            constraint=models.UniqueConstraint(fields=('entity', 'user'), name='unique entity_user'),
        ),
    ]
