# Generated by Django 4.0.4 on 2022-05-25 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0013_auto_20220522_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity_user',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
