# Generated by Django 4.0.4 on 2022-05-28 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0015_unittype_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='userid',
            field=models.ManyToManyField(default=1, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
