# Generated by Django 4.0.4 on 2022-05-28 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0016_entity_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='createdby',
        ),
        migrations.AlterField(
            model_name='entity',
            name='userid',
            field=models.ManyToManyField(default=1, related_name='uentity', to=settings.AUTH_USER_MODEL),
        ),
    ]
