# Generated by Django 4.0.4 on 2022-05-28 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0018_alter_entity_address_alter_entity_entityname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='entityName',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='ownerName',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='unitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unittype', to='entity.unittype'),
        ),
    ]
