# Generated by Django 4.0.4 on 2022-05-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0021_delete_entity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='userid',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='createdby',
        ),
    ]
