# Generated by Django 4.0.4 on 2022-05-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0022_rename_userid_entity_user_remove_entity_createdby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'verbose_name': 'unitType', 'verbose_name_plural': 'unitTypes'},
        ),
    ]
