# Generated by Django 3.2.9 on 2022-02-15 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0001_initial'),
        ('inventory', '0005_auto_20220215_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Sorderdate', models.DateTimeField(verbose_name='Sales Order date')),
                ('Duedate', models.DateTimeField(verbose_name='Due date')),
                ('Shipdate', models.DateTimeField(verbose_name='Ship date')),
                ('Staus', models.IntegerField(default=1, verbose_name='Status')),
                ('SalesOrderNumber', models.IntegerField(verbose_name='Sales Order Number')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('Taxamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax amount')),
                ('Freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Freight')),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='salesOrderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Orderqty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Qty')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('discountPercent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Percent')),
                ('discountAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount')),
                ('LineTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Line Total')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('salesOrderHeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.salesoderheader')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
