# Generated by Django 4.0.4 on 2022-06-05 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('VoucherDate', models.DateField(auto_now_add=True, verbose_name='Vocucher Date')),
                ('VoucherNo', models.IntegerField(verbose_name='Voucher No')),
                ('BillNo', models.IntegerField(verbose_name='Bill No')),
                ('BillDate', models.DateField(auto_now_add=True, verbose_name='Bill Date')),
                ('Terms', models.BooleanField(verbose_name='Terms')),
                ('TaxType', models.IntegerField(verbose_name='TaxType')),
                ('BillCash', models.IntegerField(verbose_name='Bill/Cash')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('Cgst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='C.GST')),
                ('Sgst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='S.GST')),
                ('Igst', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='I.GST')),
                ('Expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expenses')),
                ('GTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='G Total')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity', verbose_name='entity')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Sorderdate', models.DateField(auto_now_add=True, verbose_name='Sales Order date')),
                ('Duedate', models.DateField(auto_now_add=True, verbose_name='Due date')),
                ('Shipdate', models.DateField(auto_now_add=True, verbose_name='Ship date')),
                ('Staus', models.IntegerField(default=1, verbose_name='Status')),
                ('SalesOrderNumber', models.IntegerField(verbose_name='Sales Order Number')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total')),
                ('Taxamount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax amount')),
                ('Freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Freight')),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.account')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity', verbose_name='entity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='salesOrderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Orderqty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Qty')),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('discountPercent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Percent')),
                ('discountAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount Amount')),
                ('LineTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Line Total')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product')),
                ('salesOrderHeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesOrderdetails', to='invoice.salesoderheader', verbose_name='Sale Order Number')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orderqty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Qty')),
                ('pieces', models.IntegerField(verbose_name='pieces')),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('CSGT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='CGST')),
                ('SGST', models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True, verbose_name='SGST')),
                ('IGST', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGST')),
                ('HSNNo', models.CharField(max_length=255, verbose_name='HSN No')),
                ('LineTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Line Total')),
                ('createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.entity', verbose_name='entity')),
                ('purchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseOrderDetails', to='invoice.purchaseorder', verbose_name='Purchase Order Number')),
            ],
        ),
    ]
