# Generated by Django 3.2.9 on 2022-02-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20220215_1324'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoderheader',
            name='Duedate',
            field=models.DateField(auto_now_add=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='Shipdate',
            field=models.DateField(auto_now_add=True, verbose_name='Ship date'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='Sorderdate',
            field=models.DateField(auto_now_add=True, verbose_name='Sales Order date'),
        ),
        migrations.AlterField(
            model_name='salesorderdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='salesorderdetails',
            name='salesOrderHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.salesoderheader', verbose_name='Sale Order Number'),
        ),
    ]
