# Generated by Django 4.0.4 on 2022-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstransaction',
            name='goodstransactiontype',
            field=models.CharField(max_length=50, null=True, verbose_name='Goods TransactionType'),
        ),
    ]
