# Generated by Django 3.2.9 on 2022-05-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_auto_20220522_1301'),
        ('invoice', '0002_auto_20220216_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoderheader',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity', verbose_name='entity'),
        ),
    ]
