# Generated by Django 4.1 on 2022-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_goodstransaction_goodstransactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='debitamount',
            field=models.FloatField(null=True, verbose_name='Debit Amount'),
        ),
    ]
