# Generated by Django 4.1 on 2022-08-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_stocktransactions_debitamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='debitamount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Debit Amount'),
        ),
    ]
