# Generated by Django 4.1 on 2022-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_stocktransactions_creditamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoderheader',
            name='broker',
            field=models.CharField(max_length=500, null=True, verbose_name='Broker'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='shippedto',
            field=models.CharField(max_length=500, null=True, verbose_name='Shipped To'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='tcs206c1ch3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tcs 206C1cH3'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='transport',
            field=models.CharField(max_length=500, null=True, verbose_name='TransPort'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='creditamount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='debitamount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Debit Amount'),
        ),
    ]
