# Generated by Django 4.1 on 2022-08-26 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('invoice', '0011_salesoderheader_totalpieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoderheader',
            name='billcash',
            field=models.IntegerField(default=1, verbose_name='Bill/Cash'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker', to='financial.account'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='shippedto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shippedto', to='financial.account'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='taxtype',
            field=models.IntegerField(default=1, verbose_name='Tax Type'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='terms',
            field=models.IntegerField(default=1, verbose_name='Terms'),
        ),
        migrations.AlterField(
            model_name='salesoderheader',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='financial.account'),
        ),
    ]
