# Generated by Django 4.1 on 2022-08-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_remove_salesoderheader_totalweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoderheader',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='advance'),
        ),
    ]
