# Generated by Django 4.1 on 2022-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_alter_salesoderheader_latepaymentalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoderheader',
            name='latepaymentalert',
            field=models.IntegerField(default=True, null=True, verbose_name='Late Payment Alert'),
        ),
    ]
