# Generated by Django 4.1 on 2022-08-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_salesoderheader_latepaymentalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoderheader',
            name='taxid',
            field=models.IntegerField(default=0, verbose_name='Terms'),
        ),
    ]
