# Generated by Django 4.1 on 2022-09-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_purchasereturn_taxid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='purchasereturn',
            unique_together=set(),
        ),
    ]
