# Generated by Django 4.1 on 2022-09-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_alter_purchasereturn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactions',
            name='purchasereturninvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.purchasereturn', verbose_name='purchase return invoice no'),
        ),
    ]
