# Generated by Django 4.1 on 2022-09-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_purchaseorder_advance_purchaseorder_broker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='addless',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Add/Less'),
        ),
    ]
