# Generated by Django 4.1 on 2022-09-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_purchaseorder_addless'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='showledgeraccount',
            field=models.BooleanField(default=1, verbose_name='Show Ledger Account'),
        ),
    ]
