# Generated by Django 4.1 on 2022-09-04 05:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('invoice', '0025_purchaseorder_showledgeraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='addless',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Add/Less'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='advance'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='broker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srbroker', to='financial.account'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='cgstcess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='C.GST Cess'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='duedate',
            field=models.DateField(default=datetime.date.today, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='grno',
            field=models.CharField(max_length=50, null=True, verbose_name='GR No'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='gstr2astatus',
            field=models.BooleanField(default=1, verbose_name='GstR 2A Status'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='igstcess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='I.GST Cess'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='inputdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Input Date'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='remarks',
            field=models.CharField(max_length=500, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='sgstcess',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='S.GST Cess'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='showledgeraccount',
            field=models.BooleanField(default=1, verbose_name='Show Ledger Account'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='taxid',
            field=models.IntegerField(default=0, verbose_name='Terms'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tcs206C1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tcs 206C1'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tcs206C2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tcs 206C2'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tcs206c1ch1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tcs 206C1cH1'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tcs206c1ch2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tcs 206C1cH2'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tcs206c1ch3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tcs tcs206c1ch3'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tds194q',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TDS 194 @'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='tds194q1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TDS 194 @'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='totalpieces',
            field=models.IntegerField(blank=True, default=0, verbose_name='totalpieces'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='totalquanity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='totalquanity'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srtransport', to='financial.account'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='vehicle',
            field=models.CharField(max_length=50, null=True, verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='C.GST'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expenses'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='I.GST'),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='S.GST'),
        ),
    ]
